baseURL = "https://abhinavlal.in/"
languageCode = "en-us"
title = "Abhinav Lal"
theme = "kiera"
Copyright = "2018 &copy; Abhinav Lal"

[author]
    name = "Abhinav Lal"       #Author name
    github = "abhinavlal"     #Github username
    twitter = "abhinavlal"    #Twitter username
    instagram = "abhinavlal"  #Instagram username

[params]
    tagline = "Things i find interesting"
